In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("16-diabetes.csv")

In [3]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [5]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [6]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
df["Insulin"].value_counts()

Insulin
0      374
105     11
130      9
140      9
120      8
      ... 
73       1
171      1
255      1
52       1
112      1
Name: count, Length: 186, dtype: int64

In [8]:
df["BloodPressure"].value_counts()

BloodPressure
70     57
74     52
78     45
68     45
72     44
64     43
80     40
76     39
60     37
0      35
62     34
66     30
82     30
88     25
84     23
90     22
86     21
58     21
50     13
56     12
52     11
54     11
75      8
92      8
65      7
85      6
94      6
48      5
96      4
44      4
100     3
106     3
98      3
110     3
55      2
108     2
104     2
46      2
30      2
122     1
95      1
102     1
61      1
24      1
38      1
40      1
114     1
Name: count, dtype: int64

In [9]:
df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [10]:
columns_to_check = ["Glucose","BloodPressure","SkinThickness","Insulin","BMI"]

In [11]:
for col in columns_to_check:
    zero_count = (df[col] == 0).sum()
    zero_percentage = 100 * zero_count / len(df)
    print(f"{col}:{zero_count} %{zero_percentage:.2f}")

Glucose:5 %0.65
BloodPressure:35 %4.56
SkinThickness:227 %29.56
Insulin:374 %48.70
BMI:11 %1.43


In [12]:
X = df.drop("Outcome",axis=1)
y=df["Outcome"]

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=15)

In [14]:
columns_to_fill = ["Glucose","BloodPressure","SkinThickness","Insulin","BMI"]

In [15]:
medians={}
for col in columns_to_fill:
    median_value = X_train[X_train[col] !=0][col].median()
    medians[col] = median_value
    X_train[col] = X_train[col].replace(0,median_value)

for col in columns_to_fill:
    X_test[col] = X_test[col].replace(0,medians[col]) 

In [16]:
X_test.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   154.000000  154.000000     154.000000     154.000000  154.000000   
mean      3.597403  122.038961      71.487013      29.376623  144.402597   
std       3.304818   32.320876      11.813495      10.513035  104.291511   
min       0.000000   61.000000      30.000000       7.000000   23.000000   
25%       1.000000   95.250000      64.000000      23.250000  108.250000   
50%       3.000000  117.000000      72.000000      29.000000  129.500000   
75%       5.750000  142.750000      80.000000      33.750000  129.500000   
max      13.000000  197.000000     106.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age  
count  154.000000                154.000000  154.000000  
mean    32.483117                  0.479565   33.064935  
std      6.946159                  0.343303   12.118519  
min     18.400000                  0.078000   21.000000  
25%     26.925000                  0.254000   24.000000  
50%     32.300000                  0.376500   28.000000  
75%     36.950000                  0.603750   41.000000  
max     55.000000                  2.329000   69.000000

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import classification_report, accuracy_score,confusion_matrix

In [19]:
ada = AdaBoostClassifier()
ada.fit(X_train,y_train)
y_pred = ada.predict(X_test)

In [20]:
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.81      0.82       108
           1       0.58      0.63      0.60        46

    accuracy                           0.75       154
   macro avg       0.71      0.72      0.71       154
weighted avg       0.76      0.75      0.76       154

0.7532467532467533
[[87 21]
 [17 29]]


In [21]:
#hyperparameter tuning

In [22]:
from sklearn.model_selection import GridSearchCV

In [23]:
adaboost_param = {"n_estimators":[50,70,100,120,150,200],
                  "learning_rate":[0.001, 0.01,0.1,1,10]}

In [24]:
grid = GridSearchCV(estimator= AdaBoostClassifier(), param_grid= adaboost_param, cv=3, verbose=1, n_jobs=-1)

In [25]:
grid.fit(X_train, y_train)

Fitting 3 folds for each of 30 candidates, totalling 90 fits


GridSearchCV(cv=3, estimator=AdaBoostClassifier(), n_jobs=-1,
             param_grid={'learning_rate': [0.001, 0.01, 0.1, 1, 10],
                         'n_estimators': [50, 70, 100, 120, 150, 200]},
             verbose=1)

In [26]:
grid.best_params_

{'learning_rate': 1, 'n_estimators': 200}

In [27]:
ada = AdaBoostClassifier(learning_rate=1,n_estimators=200)

In [28]:
ada.fit(X_train,y_train)
y_pred = ada.predict(X_test)

In [29]:
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.80      0.82       108
           1       0.57      0.63      0.60        46

    accuracy                           0.75       154
   macro avg       0.70      0.71      0.71       154
weighted avg       0.76      0.75      0.75       154

0.7467532467532467
[[86 22]
 [17 29]]


In [34]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

In [59]:
params = {}
classification_models = {"SVC":SVC(),"LogisticRegression":LogisticRegression(),"GaussianNB":GaussianNB(),"DecisionTreeClassifier":DecisionTreeClassifier(),"KNeighborsClassifier":KNeighborsClassifier(),"RandomForestClassifier":RandomForestClassifier()}

In [60]:
for i in range(len(list(classification_models))):
    model = list(classification_models.values())[i]
    model.fit(X_train, y_train)
    y_test_pred = model.predict(X_test)
    y_train_pred = model.predict(X_train)
    print(model)
    print("-----------------------------")
    print("TEST:\n")
    print("Accuracy Score: ", accuracy_score(y_test, y_test_pred))
    print("Confusion Matrix:\n ", confusion_matrix(y_test, y_test_pred))
    print("Classification Report: ", classification_report(y_test, y_test_pred))
    print("\n")
    print("TRAIN:\n")
    print("Accuracy Score: ", accuracy_score(y_train, y_train_pred))
    print("Confusion Matrix:\n ", confusion_matrix(y_train, y_train_pred))
    print("Classification Report: ", classification_report(y_train, y_train_pred))
    print("------------------------------")
    print("\n")

SVC()
-----------------------------
TEST:

Accuracy Score:  0.7272727272727273
Confusion Matrix:
  [[87 21]
 [21 25]]
Classification Report:                precision    recall  f1-score   support

           0       0.81      0.81      0.81       108
           1       0.54      0.54      0.54        46

    accuracy                           0.73       154
   macro avg       0.67      0.67      0.67       154
weighted avg       0.73      0.73      0.73       154



TRAIN:

Accuracy Score:  0.8387622149837134
Confusion Matrix:
  [[362  30]
 [ 69 153]]
Classification Report:                precision    recall  f1-score   support

           0       0.84      0.92      0.88       392
           1       0.84      0.69      0.76       222

    accuracy                           0.84       614
   macro avg       0.84      0.81      0.82       614
weighted avg       0.84      0.84      0.83       614

------------------------------


LogisticRegression()
-----------------------------
TEST:



In [90]:
params["SVC"] = {
    "C": [0.001, 0.01, 0.1, 1, 10],
    "kernel": ["linear", "poly", "rbf", "sigmoid"],
    "degree": [2, 3, 4],       
    "gamma": ["scale", "auto"],
    "max_iter": [1000, 5000]
}
params["LogisticRegression"] = [
    {   
        "penalty": ["l2"],
        "C": [0.001, 0.01, 0.1, 1, 10],
        "solver": ["lbfgs", "saga"],
        "max_iter": [1000]
    },
    {   
        "penalty": ["l1"],
        "C": [0.001, 0.01, 0.1, 1, 10],
        "solver": ["liblinear", "saga"],
        "max_iter": [1000]
    }
]
params["DecisionTreeClassifier"] = {
    "criterion": ["gini", "entropy", "log_loss"],
    "splitter": ["best", "random"],
    "max_depth": [None, 3, 5, 10, 20],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": [None, "sqrt", "log2"]
}
params["KNeighborsClassifier"] = {
    "n_neighbors": [3, 5, 7, 9, 11],
    "weights": ["uniform", "distance"],
    "algorithm": ["auto", "ball_tree", "kd_tree", "brute"],
    "p": [1, 2]   
}
params["RandomForestClassifier"] = {
    "n_estimators": [100, 200, 300],
    "criterion": ["gini", "entropy", "log_loss"],
    "max_depth": [None, 5, 10, 20],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": ["sqrt", "log2"]
}
params["GaussianNB"] = {
    "var_smoothing": [1e-9, 1e-8, 1e-7, 1e-6]
}

In [88]:
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings("ignore")

In [91]:
for i in range(len(list(classification_models))):
    model = list(classification_models.values())[i]
    model_name = list(classification_models.keys())[i]
    grid = GridSearchCV(estimator=model,param_grid=params[model_name],scoring="accuracy",n_jobs=-1)
    grid.fit(X_train, y_train)
    y_test_pred = grid.predict(X_test)
    y_train_pred = grid.predict(X_train)
    print(model)
    print("-----------------------------")
    print("TEST:\n")
    print("Accuracy Score: ", accuracy_score(y_test, y_test_pred))
    print("Confusion Matrix:\n ", confusion_matrix(y_test, y_test_pred))
    print("Classification Report: ", classification_report(y_test, y_test_pred))
    print("\n")
    print("TRAIN:\n")
    print("Accuracy Score: ", accuracy_score(y_train, y_train_pred))
    print("Confusion Matrix:\n ", confusion_matrix(y_train, y_train_pred))
    print("Classification Report: ", classification_report(y_train, y_train_pred))
    print("------------------------------")
    print("\n")

SVC()
-----------------------------
TEST:

Accuracy Score:  0.7597402597402597
Confusion Matrix:
  [[92 16]
 [21 25]]
Classification Report:                precision    recall  f1-score   support

           0       0.81      0.85      0.83       108
           1       0.61      0.54      0.57        46

    accuracy                           0.76       154
   macro avg       0.71      0.70      0.70       154
weighted avg       0.75      0.76      0.76       154



TRAIN:

Accuracy Score:  0.7736156351791531
Confusion Matrix:
  [[353  39]
 [100 122]]
Classification Report:                precision    recall  f1-score   support

           0       0.78      0.90      0.84       392
           1       0.76      0.55      0.64       222

    accuracy                           0.77       614
   macro avg       0.77      0.73      0.74       614
weighted avg       0.77      0.77      0.76       614

------------------------------


LogisticRegression()
-----------------------------
TEST:



In [40]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [92]:
df_insulin_droped = df.drop("Insulin",axis=1)
X = df_insulin_droped.drop("Outcome", axis=1)
y = df_insulin_droped["Outcome"]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=15)
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [93]:
df_insulin_droped.head()

Pregnancies  Glucose  BloodPressure  SkinThickness   BMI  \
0            6      148             72             35  33.6   
1            1       85             66             29  26.6   
2            8      183             64              0  23.3   
3            1       89             66             23  28.1   
4            0      137             40             35  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [94]:
for i in range(len(list(classification_models))):
    model = list(classification_models.values())[i]
    model_name = list(classification_models.keys())[i]
    grid = GridSearchCV(estimator=model,param_grid=params[model_name],scoring="accuracy",n_jobs=-1)
    grid.fit(X_train, y_train)
    y_test_pred = grid.predict(X_test)
    y_train_pred = grid.predict(X_train)
    print(model)
    print("-----------------------------")
    print("TEST:\n")
    print("Accuracy Score: ", accuracy_score(y_test, y_test_pred))
    print("Confusion Matrix:\n ", confusion_matrix(y_test, y_test_pred))
    print("Classification Report: ", classification_report(y_test, y_test_pred))
    print("\n")
    print("TRAIN:\n")
    print("Accuracy Score: ", accuracy_score(y_train, y_train_pred))
    print("Confusion Matrix:\n ", confusion_matrix(y_train, y_train_pred))
    print("Classification Report: ", classification_report(y_train, y_train_pred))
    print("------------------------------")
    print("\n")

SVC()
-----------------------------
TEST:

Accuracy Score:  0.7662337662337663
Confusion Matrix:
  [[94 14]
 [22 24]]
Classification Report:                precision    recall  f1-score   support

           0       0.81      0.87      0.84       108
           1       0.63      0.52      0.57        46

    accuracy                           0.77       154
   macro avg       0.72      0.70      0.71       154
weighted avg       0.76      0.77      0.76       154



TRAIN:

Accuracy Score:  0.7882736156351792
Confusion Matrix:
  [[364  28]
 [102 120]]
Classification Report:                precision    recall  f1-score   support

           0       0.78      0.93      0.85       392
           1       0.81      0.54      0.65       222

    accuracy                           0.79       614
   macro avg       0.80      0.73      0.75       614
weighted avg       0.79      0.79      0.78       614

------------------------------


LogisticRegression()
-----------------------------
TEST:

